"""Export the heterogeneous graph to formats other tools understand.

Two targets, both plain files and neither requiring the tool to be installed:

* **CSV** — one file per node type and one per relation type, in the shape
  `neo4j-admin import` expects (`:ID`, `:LABEL`, `:START_ID`, `:END_ID`,
  `:TYPE`). The same files load straight into DuckDB or pandas.
* **Cypher** — a single idempotent script of `MERGE` statements, for when you
  just want to paste it into a running Neo4j browser.

The purpose is to make the later "would a real graph database be better?"
comparison cheap, not to move to one now.
"""
from __future__ import annotations

import csv
import json
from pathlib import Path
from typing import Dict, List

from .schema import NODE_TYPES

# Properties that are structural bookkeeping rather than data.
SKIP = {"id", "type", "geometry", "provenance"}
# Neo4j has no nested values; these are flattened to JSON text instead.
JSON_FIELDS = {"vehicles"}


def _scalar(value):
    if isinstance(value, (list, tuple, dict)):
        return json.dumps(value, ensure_ascii=False)
    if value is None:
        return ""
    return value


def _columns(rows: List[dict]) -> List[str]:
    seen: List[str] = []
    for row in rows:
        for key in row:
            if key not in SKIP and key not in seen:
                seen.append(key)
    return seen


def to_csv(graph, out_dir, include_geometry: bool = False) -> dict:
    """Write `nodes_<Type>.csv` and `edges_<RELATION>.csv` into `out_dir`."""
    out_dir = Path(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    written: Dict[str, dict] = {"nodes": {}, "edges": {}}

    for node_type in NODE_TYPES:
        rows = list(graph.nodes_of_type(node_type))
        if not rows:
            continue
        columns = _columns(rows)
        if include_geometry:
            columns.append("geometry")
        path = out_dir / f"nodes_{node_type}.csv"
        with path.open("w", newline="", encoding="utf-8") as handle:
            writer = csv.writer(handle)
            writer.writerow(["id:ID", ":LABEL"] + columns)
            for row in rows:
                writer.writerow([row["id"], node_type] + [_scalar(row.get(c)) for c in columns])
        written["nodes"][node_type] = {"path": path.name, "rows": len(rows),
                                       "columns": columns}

    by_relation: Dict[str, List[tuple]] = {}
    for source, target, relation, data in graph.graph.edges(keys=True, data=True):
        by_relation.setdefault(relation, []).append((source, target, data))
    for relation, rows in sorted(by_relation.items()):
        columns = _columns([data for _, _, data in rows])
        columns = [c for c in columns if c != "relation"]
        path = out_dir / f"edges_{relation}.csv"
        with path.open("w", newline="", encoding="utf-8") as handle:
            writer = csv.writer(handle)
            writer.writerow([":START_ID", ":END_ID", ":TYPE"] + columns)
            for source, target, data in rows:
                writer.writerow([source, target, relation]
                                + [_scalar(data.get(c)) for c in columns])
        written["edges"][relation] = {"path": path.name, "rows": len(rows),
                                      "columns": columns}

    manifest = {
        "format": "neo4j-admin import / DuckDB read_csv compatible",
        "generated_from": graph.metadata.get("generated_at"),
        "graph_mode": graph.metadata.get("mode"),
        "include_geometry": include_geometry,
        **written,
        "neo4j_import_hint": (
            "neo4j-admin database import full "
            + " ".join(f"--nodes={v['path']}" for v in written["nodes"].values())
            + " " + " ".join(f"--relationships={v['path']}" for v in written["edges"].values())
        ),
        "duckdb_hint": "SELECT * FROM read_csv_auto('nodes_Neighborhood.csv')",
    }
    (out_dir / "manifest.json").write_text(json.dumps(manifest, indent=2), encoding="utf-8")
    return manifest


def to_cypher(graph, path, include_geometry: bool = False) -> Path:
    """One idempotent MERGE script. Readable, and it needs no import tooling."""
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)

    def literal(value) -> str:
        value = _scalar(value)
        if isinstance(value, bool):
            return "true" if value else "false"
        if isinstance(value, (int, float)):
            return repr(value)
        return json.dumps(str(value), ensure_ascii=False)

    lines = [
        "// Basel Spatial Graph — generated by app.spatial_graph.export",
        f"// graph built {graph.metadata.get('generated_at')} "
        f"({graph.metadata.get('mode')} data)",
        "",
    ]
    for node_type in NODE_TYPES:
        rows = list(graph.nodes_of_type(node_type))
        if not rows:
            continue
        lines.append(f"// --- {node_type} ({len(rows)}) ---")
        for row in rows:
            properties = {k: v for k, v in row.items()
                          if k not in SKIP or (k == "geometry" and include_geometry)}
            assignments = ", ".join(f"n.{k} = {literal(v)}" for k, v in properties.items())
            lines.append(f"MERGE (n:{node_type} {{id: {literal(row['id'])}}})"
                         + (f" SET {assignments};" if assignments else ";"))
        lines.append("")
    for source, target, relation, data in graph.graph.edges(keys=True, data=True):
        properties = {k: v for k, v in data.items() if k != "relation"}
        assignments = ", ".join(f"r.{k} = {literal(v)}" for k, v in properties.items())
        lines.append(
            f"MATCH (a {{id: {literal(source)}}}), (b {{id: {literal(target)}}}) "
            f"MERGE (a)-[r:{relation}]->(b)" + (f" SET {assignments};" if assignments else ";"))
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return path


def schema_cypher() -> str:
    """Constraints and indexes matching the schema, for a real Neo4j load."""
    lines = ["// Constraints and indexes for the Basel Spatial Graph", ""]
    for name in NODE_TYPES:
        lines.append(f"CREATE CONSTRAINT {name.lower()}_id IF NOT EXISTS "
                     f"FOR (n:{name}) REQUIRE n.id IS UNIQUE;")
    lines.append("")
    lines.append("CREATE INDEX neighborhood_children IF NOT EXISTS "
                 "FOR (n:Neighborhood) ON (n.children);")
    lines.append("CREATE INDEX service_category IF NOT EXISTS "
                 "FOR (n:ServiceLocation) ON (n.category);")
    return "\n".join(lines) + "\n"
